# Generated by Django 2.1.7 on 2019-04-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_auto_20190407_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('search_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('search_max_distance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('distance_metric', models.CharField(choices=[('m', 'metric'), ('i', 'imperial')], max_length=1)),
                ('no_of_matches', models.IntegerField()),
                ('search_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='search_person', to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Search_Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance_in_selected_unit', models.DecimalField(decimal_places=1, max_digits=5)),
                ('match_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_person', to='donation_requests.Search')),
            ],
        ),
    ]
