# Generated by Django 2.1.7 on 2019-04-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20190407_2215'),
        ('donation_requests', '0002_auto_20190409_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_For_Donation',
            new_name='RequestForDonation',
        ),
        migrations.RenameModel(
            old_name='Search_Matches',
            new_name='SearchMatches',
        ),
    ]
