# Generated by Django 2.1.7 on 2019-04-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0004_auto_20190409_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmatches',
            name='distance_in_metres',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
