# Generated by Django 2.1.7 on 2019-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0005_auto_20190409_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='distance_metric',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search_max_distance',
        ),
        migrations.AddField(
            model_name='search',
            name='search_max_distance_metres',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
