# Generated by Django 2.1.7 on 2019-04-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation_requests', '0010_auto_20190415_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfordonation',
            name='person_donation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_donation_request', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='requestfordonation',
            name='search_match_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_search_match', to='donation_requests.SearchMatches'),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_search', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='searchmatches',
            name='match_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_match', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='searchmatches',
            name='search_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_match', to='donation_requests.Search'),
        ),
    ]
