# Generated by Django 2.1.7 on 2019-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_blood_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
